---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# microsim-disability

<!-- badges: start -->
<!-- badges: end -->

# Import data and model

```{r}
library(dymiumCore)
library(data.table)

n_agents <- 1000L

population <- 
  data.table(
    pid = 1:n_agents,
    age = sample(0:100, n_agents, replace = T),
    sex = sample(c("female", "male"), n_agents, replace = T),
    state = sample(c("healthy", "mild", "severe"), n_agents, replace = T)
  ) 

w <- World$new()
a <- Agent$new(.data = population, id_col = "pid")

w$add(a, name = "Agent")

trans_model <-
  fread("data/tprob.csv") %>%
  .[, `:=`(probs = .(c(healthy, mild, severe, death)),
           choices = .(c("healthy", "mild", "severe", "death"))), 
    by = 1:nrow(.)] %>%
  setnames(old = "from", new = "state") %>%
  .[, sex := ifelse(female == 1, "female", "male")] %>%
  .[, c("healthy", "mild", "severe", "death", "female") := NULL]
```

# Create microsimulation events

```{r}
event_disability <- function(w, model) {
  
  Agt <- w$get("Agent")
  
  eligible_agent_ids <- Agt$get_data()[age > 50, get(Agt$get_id_col())]
  
  TransitionDisability <- TransitionClassification$new(x = Agt, 
                                                       model = model, 
                                                       targeted_agents = eligible_agent_ids)
  
  print(TransitionDisability)
  
  TransitionDisability$update_agents(attr = "state")
  
  dead_agent_ids <- Agt$get_data()[state == "death", get(Agt$get_id_col())]
  
  if (length(dead_agent_ids) != 0) {
    message("Removing ", length(dead_agent_ids), " agents in 'death' state.")
    Agt$remove(ids = dead_agent_ids)
  }
  
  Agt$log(desc = "disability:state", value = xtabs(~ state, data = Agt$get_data()))
  
  return(w)
}


event_age <- function(w) {
  Agt <- w$get("Agent")
  
  # update age of agents, with max of 114.
  Agt$get_data(copy = FALSE)[, age := ifelse(age + 1L > 114L, 114L, age + 1L)]
  
  return(w)
}
```


# Microsimulation pipeline

```{r}
for (i in 1:10) {
  w %>%
    event_age(.) %>%
    event_disability(., trans_model)
}
```

# Visualisation

```{r}
get_log(w)
```

